apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: ops-webapp-setup
spec:
  connection_secret: aap-controller-access
  name: ops-webapp-setup
  project: ansible-playbooks 
  playbook: webapp-setup.yaml
  inventory: openshift-endor
  execution_environment: "Default execution environment" 
  credentials: 
    - "ansible-machine"