apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: ops-vm-snapshot
spec:
  connection_secret: aap-controller-access
  name: ops-vm-snapshot
  project: ansible-playbooks
  playbook: snapshot-vm-task.yaml
  inventory: openshift-endor
  execution_environment: "Default execution environment" 
  credentials: 
    - "openshift-endor"